// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD32VKu6FP1SNXEtfJJhtCZ8kpQyoOA75k',
    appId: '1:451748288695:web:f710a54f45bd937fc69532',
    messagingSenderId: '451748288695',
    projectId: 'bingo-app-jogador',
    authDomain: 'bingo-app-jogador.firebaseapp.com',
    storageBucket: 'bingo-app-jogador.appspot.com',
    measurementId: 'G-T7TSZQ5Y8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ji6kk_yzvYVCQSEy34bM62nl6jENUDA',
    appId: '1:451748288695:android:c38a39e811422636c69532',
    messagingSenderId: '451748288695',
    projectId: 'bingo-app-jogador',
    storageBucket: 'bingo-app-jogador.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ZfM9tYmQN6kG0e8aoI80DFXDFaX9kSM',
    appId: '1:451748288695:ios:9cdfdf40a0bfffe9c69532',
    messagingSenderId: '451748288695',
    projectId: 'bingo-app-jogador',
    storageBucket: 'bingo-app-jogador.appspot.com',
    iosBundleId: 'br.com.fabioalvaro.bingoJogador',
  );

}